"""Add purchase orders

Revision ID: dff8427b9ade
Revises: 3d005a346627
Create Date: 2026-01-11 17:50:33.339905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff8427b9ade'
down_revision = '3d005a346627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('po_type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('terms', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_number'), ['number'], unique=True)

    op.create_table('purchase_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_document_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_document_updated_at'))

    op.drop_table('purchase_order_item')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_date'))

    op.drop_table('purchase_order')
    # ### end Alembic commands ###
